import time
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from locators.login_page_locators import *
import allure


@allure.suite("Переход с главной страницы в профили гостей")
def test_autorize_user_guest_profiles(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    assert driver.current_url == "https://lk.reliz-br-onl.ru/numbers/guest/profile"


@allure.suite("Создание профилей гостей без гражданства")
@allure.title("Создания гостя без гражданства (цифры)")
def test_adding_guest_from_numbers(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_comment))
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys(111)
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys(222)
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys(333)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    assert first_guest.text.strip() == "222 111 333"


@allure.title("Создания гостя без гражданства (кириллица)")
def test_adding_guest_from_kirilica(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Влад")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Тест")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Авто")
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    assert first_guest.text.strip() == "Тест Влад Авто"


@allure.title("Создания гостя без гражданства (латиница)")
def test_adding_guest_from_latinica(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_comment))
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Vlad")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Test")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Auto")
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    assert first_guest.text.strip() == "Test Vlad Auto"


@allure.title("Создания гостя без гражданства с комментарием")
def test_adding_guest_from_comment(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_comment))
    comment = driver.find_element(*GuestProfiles.inp_comment)
    comment.click()
    comment.send_keys("Здравствуйте my name is VLADISLAV")
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Влад")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Тест")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Коммент")
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    guest_comment = driver.find_element(*GuestProfiles.guest_comment)
    assert first_guest.text.strip() == "Тест Влад Коммент"
    assert guest_comment.text.strip() == "Здравствуйте my name is VLADISLAV"

@allure.title("Создания гостя без гражданства со статусом VIP")
def test_adding_guest_from_status_vip(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_VIP)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Влад")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Вип")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_guest.text.strip() == "Вип Влад Тест"
    assert first_status.text.strip() == "VIP"

@allure.title("Создания гостя без гражданства со статусом Постоянный гость")
def test_adding_guest_from_status_regular(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_regular)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Влад")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Постоянный")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_status.text.strip() == "Постоянный гость"

@allure.title("Создания гостя без гражданства со статусом Черный список")
def test_adding_guest_from_status_blacklist(driver, autorize_user, hotel_switch):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_blacklist)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Влад")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Черныйсписок")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_guest.text.strip() == "Черныйсписок Влад Тест"
    assert first_status.text.strip() == "Черный список"


@allure.title("Создания гостя без гражданства с д.р. телефоном почтой и статусом")
def test_adding_guest_from_no_status_telephone_birthday(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_no_status)).click()
    comment = driver.find_element(*GuestProfiles.inp_comment)
    comment.click()
    comment.send_keys("I'm not empty")
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Влад")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Заполненный")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    driver.find_element(*GuestProfiles.checkbox_man).click()
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(11111111)
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    guest_comment_status = driver.find_element(*GuestProfiles.guest_comment)
    birthday_status = driver.find_element(*GuestProfiles.first_birthday)
    first_email = driver.find_element(*GuestProfiles.first_email)
    assert birthday_status.text.strip() == "11.11.1111"
    assert first_email.text.strip() == email_value
    assert first_status.text.strip() == "Без статуса"
    assert guest_comment_status.text.strip() == "I'm not empty"


@allure.title("Создания гостя гражданство рф без статуса")
def test_adding_guest_russia_no_status(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_no_status)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Владислав")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Россия")
    driver.find_element(*GuestProfiles.checkbox_no_surname).click()
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(11111111)
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_status.text.strip() == "Без статуса"


@allure.title("Создания гостя гражданство рф VIP")
def test_adding_guest_russia_vip(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_VIP)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Вип")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Россия")
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(11111111)
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_status.text.strip() == "VIP"


@allure.title("Создания гостя гражданство рф Постоянный гость")
def test_adding_guest_russia_regular(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_regular)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Постоянный")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Россия")
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(11112001)
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_status.text.strip() == "Постоянный гость"


@allure.title("Создания гостя гражданство рф Черный список")
def test_adding_guest_russia_black_list(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_blacklist)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Владиславчс")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Россия")
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(11112000)
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    first_status = driver.find_element(*GuestProfiles.first_user_status)
    assert first_status.text.strip() == "Черный список"

@allure.title("Создания гостя(РФ) с федеральной льготой")
def test_adding_guest_russia_federal(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_no_status)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Владислав")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Фереральнаяльгота")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(12112005)
    driver.find_element(*GuestProfiles.checkbox_privileged_category).click()
    driver.find_element(*GuestProfiles.inp_privileged_category).click()
    wait.until(ec.element_to_be_clickable(GuestProfiles.federal_priveleged)).click()
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    assert first_guest.text.strip() == "Фереральнаяльгота Владислав Тест"


@allure.title("Создания гостя(РФ) с местной льготой")
def test_adding_guest_russia_local(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_no_status)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Владислав")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Местнаяльгота")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(12112005)
    driver.find_element(*GuestProfiles.checkbox_privileged_category).click()
    driver.find_element(*GuestProfiles.inp_privileged_category).click()
    wait.until(ec.element_to_be_clickable(GuestProfiles.local_priveleged)).click()
    justification = driver.find_element(*GuestProfiles.justification)
    justification.click()
    justification.send_keys("Потому что человек местный вот и льгота местная!")
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.button_save_guest).click()
    driver.get("https://lk.reliz-br-onl.ru/numbers/guest/profile")
    first_guest = WebDriverWait(driver, 10).until(ec.visibility_of_element_located(GuestProfiles.first_guest_list))
    assert first_guest.text.strip() == "Местнаяльгота Владислав Тест"


@allure.title("Создания гостя(РФ) полностью заполненная карточка со статусом Готовы к отправке")
def test_adding_guest_russia_full_card(driver, autorize_user, hotel_switch, email_value, phone_value):
    driver.find_element(*SideMenuLocators.guest_profiles).click()
    driver.find_element(*GuestProfiles.add_guest_button).click()
    wait = WebDriverWait(driver, 10)
    wait.until(ec.visibility_of_element_located(GuestProfiles.inp_no_status))
    driver.find_element(*GuestProfiles.inp_no_status).click()
    wait.until(ec.visibility_of_element_located(GuestProfiles.drop_no_status)).click()
    citizenship_rus = driver.find_element(*GuestProfiles.inp_citizenship)
    citizenship_rus.click()
    citizenship_rus.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.citizenship_russia)).click()
    firstname = driver.find_element(*GuestProfiles.inp_firstname)
    firstname.click()
    firstname.send_keys("Владислав")
    lastname = driver.find_element(*GuestProfiles.inp_lastname)
    lastname.click()
    lastname.send_keys("Готовкотправке")
    surname = driver.find_element(*GuestProfiles.inp_surname)
    surname.click()
    surname.send_keys("Тест")
    driver.find_element(*GuestProfiles.checkbox_man).click()
    birthday = driver.find_element(*GuestProfiles.birthday)
    birthday.click()
    birthday.send_keys(12112005)
    telephone = driver.find_element(*GuestProfiles.placeholder_phone)
    telephone.click()
    telephone.send_keys(phone_value)
    email = driver.find_element(*GuestProfiles.placeholder_email)
    email.click()
    email.send_keys(email_value)
    driver.find_element(*GuestProfiles.document_type).click()
    wait.until(ec.element_to_be_clickable(GuestProfiles.passport_rus)).click()
    ser = wait.until(ec.element_to_be_clickable(GuestProfiles.input_series))
    ser.click()
    ser.send_keys("3812")
    number = wait.until(ec.element_to_be_clickable(GuestProfiles.input_number))
    number.click()
    number.send_keys("087887")
    issue = driver.find_element(*GuestProfiles.input_date_issue)
    issue.click()
    issue.send_keys(11101995)
    deport1 = driver.find_element(*GuestProfiles.input_department_code)
    deport1.click()
    deport1.send_keys("111")
    wait.until(ec.element_to_be_clickable(GuestProfiles.dep_code_moscow)).click()
    deport2 = driver.find_element(*GuestProfiles.input_kem_vidan)
    deport2.click()
    gos = driver.find_element(*GuestProfiles.input_gos)
    gos.click()
    gos.send_keys("Россия")
    wait.until(ec.element_to_be_clickable(GuestProfiles.drop_rus)).click()
    reg = driver.find_element(*GuestProfiles.input_reg)
    reg.click()
    reg.send_keys("Курск")
    driver.find_element(*GuestProfiles.checkbox_no_registration).click()
    element = wait.until(ec.visibility_of_element_located(GuestProfiles.status_mvd_on))
    assert "Готовы к отправке" in element.text
    driver.find_element(*GuestProfiles.button_save_guest).click()



